# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6acde0e6b9c324687faca1702318341ce94c6a27d4c0a5a27b5bbf2b5b9f995acb340d6a546b96589a81dde48d1336f9b0438782b91f4a41ac10ee3bdfd69b44

test:
  secret_key_base: 49a8b0a2290313d63ad5659273170ffe45d5e19474fb43cd1f298d90beea1233b7707ace38c446077c08a35318e974794e7b5df122cf5486827394e4a68988ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
